name: Buildifier check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  Buildifier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Bazel
        uses: abhinavsingh/setup-bazel@v3
        with:
          version: 3.5.1

      - name: Buildifier
        run: bazel run //:buildifier