name: Clang Format
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  clang-format-checking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: RafikFarhad/clang-format-github-action@v1
        with:
          style: 'Google'
          sources: "cpps/**/*.h,cpps/**/*.cpp"