name: Clang Format
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  clang-format-checking:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.10
      with:
        source: '.'
        exclude: ''
        extensions: 'h,cpp'
        clangFormatVersion: 10
        style: Google